language: python
python:
  - "3.4"
install:
  - pip install setuptools
  - wget https://github.com/kopchik/useful/archive/master.zip
  - unzip master.zip
  - cd useful-master && sudo ./setup.py install
script: ./run-tests.sh
